### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by JoaoGSRocha** [larsks/gitdriver#13]
After inserting the code from the webpage as requested: 

`Enter code: xxxxxxxxxxxxxxxxxxxx
Create repository "PRXXX"
Initialized empty Git repository in C:/Users/Torre/BrainCrack/gitdriver/PRXXX/.git/
Traceback (most recent call last):
  File "gitdriver.py", line 74, in <module>
    main()
  File "gitdriver.py", line 52, in main
    for rev in gd.revisions(opts.docid):
  File "C:\Users\Torre\BrainCrack\gitdriver\drive.py", line 169, in revisions
    for rev in r['items']:
KeyError: 'items'`

**Comment by JoaoGSRocha** [comment]
This was only happening cause I was accidentally trying to apply this to a folder of several documents, my mistake

**Comment by larsks** [comment]
My favorite kind of problem report :). Thanks!
